name: krishnarestart

on: 
  push:
    branches:
      - feature
      - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build completed"
      - run: echo "verygood learning"
